title: Nomadic How Far
author: Isaac R
email: reichmantech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Come with me on my initial spurt of travels as a digital nomad.
  I believe that society is important, but that our natural state is as adventurers.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ilr1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
